language: java

sudo: required

addons:
  sonarcloud:
    organization: francescoterrosi-github
    token:
      secure: "LDAbYXPgpVybm7EOOtSF8jYAALz7dzYkZs9pvjCUn5Pnc37X+aYSCYqf3yftr8D4oAzykLnSTpuwDfYBx5OSZOMgpPFmoRj32suFlUb7/UNOyFo2KFTEcKuHMCoifJ1/dRwAeSYs83QP8/2ne5rS/LVJUShkjXf36BYxQHhOerhIfwY2lyHWgN3Gaz7okZy1MTv6ny3qfHn9TY+ygiQCOZTLKBPN9K9M2rzdKyz98lrpeXdV/w8kmK/AysZ/dqnPMqUU59nggtXCS33DLyKUFHSTzde5qpBVFi32sHwF1DSF4dQSzrcz7G5IoyE1wZE6Va9txdNZPVywfUC/56IwHOM3fg7mSmgr/CiBBhaLL33meRPQSIjtv1FnOBCuE61WWk0MJI8SDjF5gEkFGa1sNeFB4BP2MFhM75AHN6/o18+IOIz40862kci+dGy/EQjpv7drRMdc4uxqVwVhAvlfzorLFcFPBU8c8soQ7xIGKY0I8xy/wTYAZWQwfLW1imf+HWe8EtLj3vdGNxPDt5JWez414k9VxUn7Lc8bU+I5YtkwuDbXfiIG01s09YzF+8ymfJcL6qYfmiiH6Uf+3gRt+IHCbU1hanRlwz9V8UDHmCE+kIVJCjK8F2bPsGUgeOwhWmkmncVTMx+ANfZVuuFZkQO0FWKwU84rSRXCFMsi/QU="

jdk:
  - oraclejdk8

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

script:
  - mvn -f rehearsal-room/pom.xml clean verify -Pjacoco coveralls:report sonar:sonar
