language: java

sudo: required

addons:
  sonarcloud:
    organization: francescoterrosi-github
    token:
      secure: "xN4zFTHK4SEzXhQ7qLXxuXmkd2FrRusFDuH9uNslaIXiBcFqSSt8kHDK4STHRo2OXbYT/yJ29FkXpC7FrDMnS2oR1kb9y/gt4eKxXiehyD1qP+9mrjOoDvkhG9s5ONz3oRaQVn46FIAepJJmzPQUmlPN4qlQUUfA3xUBDndIRw3m/phV+AETZ7RyzwLFEnd6KRyt+7dkLv70LQoVeFVV0mYukEfrwqzSBRg2gbkPO+4+uA/H9/ktbOKFQGV3lqXv4QPcIVBFKosqxfHTWHicfwHm0VkZ5geHAMzNHFPOLaZhkkrAOW7I8PlPUzZBL1XdeMySO053coBWiZ5r08nnxU3W4kMpF/VWqKLYMZENF4NGUl+7v5CXRFK10QqE6QTvOfTo9PksPLQTdzVPoab5LGilHrQMs1Rv1JQALvxeB9l0JtK1NK42+7zHoLYCiDaYxJpsxFFDfEbddfUMf7X6ADcTsRuqUQn7D99r9JVwqG84MTtQYjx3UNhg26WHNs8HLpnh1V3O5v3JzJaaB/zckfym0lOWEnCfrrLOiL1MY4nhQ9iDRYia+oUGP2wZtswMGkpoWrBpUwbtiO0Ce9ILk2zXHcJfFflSbcEcoVqdKQSUO8WviJo0tnWAguJmdGiwdDb62bMgn90CoBriDol3cZ4LLO6Lfwdd9v4ncPQe5YY="


jdk:
  - oraclejdk8

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

script:
  - mvn -f rehearsal-room/pom.xml clean verify -Pjacoco coveralls:report sonar:sonar
